#!/usr/bin/env python3
"""local-sandbox-fix Harness：init / gate / resume / finalize / abort。"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

_OMNI_STATE: Any = None

GATE_STEPS = [
    "0-init",
    "2-start-ci",
    "3-wait-ci",
    "4-parse-result",
    "5-fix-verify",
    "6-code-review-gate",
    "7-record-iteration",
]

LOOP_STEPS = GATE_STEPS[1:]

SESSION_START_MARKER = "=== 执行开始 ==="
GIT_SUMMARY_NAME = "git_summary.txt"


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _require_dir(value: str, flag: str) -> Path:
    if not (value or "").strip():
        print(json.dumps({"errors": [f"{flag} is required"]}, ensure_ascii=False))
        sys.exit(2)
    path = Path(value).resolve()
    if not path.is_dir():
        print(json.dumps({"errors": [f"{flag} is not a directory: {path}"]}, ensure_ascii=False))
        sys.exit(2)
    return path


def _load_omnispec_state(plugin_root: Path) -> Any:
    """动态加载 omni-dsdd/scripts/python/omnispec_state.py（与 design_harness 同款做法）。"""
    global _OMNI_STATE
    if _OMNI_STATE is not None:
        return _OMNI_STATE
    lib_path = plugin_root / "scripts" / "python" / "omnispec_state.py"
    if not lib_path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("omnispec_state", lib_path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    _OMNI_STATE = module
    return module


def _resolve_feature_dir_from_records(plugin_root: Path, working_dir: Path) -> Optional[Path]:
    """未显式传 --feature-dir 时，从记录文件解析（.active-feature / changes/*/.runs/.omnispec-state.json / 环境变量）。"""
    state = _load_omnispec_state(plugin_root)
    if state is None:
        return None
    try:
        resolved = state.resolve_feature_dir(working_dir=working_dir, plugin_root=plugin_root)
    except Exception:
        return None
    return Path(resolved) if resolved else None


def _harness_dir_from_args(args: argparse.Namespace) -> Path:
    if getattr(args, "harness_dir", None):
        return Path(args.harness_dir).resolve()
    print(json.dumps({"errors": ["--harness-dir is required (harness 产物位于 ${FEATURE_DIR}/.runs/local-sandbox-fix)"]}, ensure_ascii=False))
    sys.exit(2)


def _load_paths(harness_dir: Path) -> Dict[str, Any]:
    path = harness_dir / "paths.json"
    if not path.is_file():
        raise FileNotFoundError(f"paths.json not found: {path}")
    return _read_json(path)


def _manifest_path(harness_dir: Path) -> Path:
    return harness_dir / "run-manifest.json"


def _load_manifest(harness_dir: Path) -> Dict[str, Any]:
    return _read_json(_manifest_path(harness_dir))


def _save_manifest(harness_dir: Path, manifest: Dict[str, Any]) -> None:
    manifest["updated_at"] = _utc_now()
    _write_json(_manifest_path(harness_dir), manifest)


def _build_paths(plugin_root: Path, working_dir: Path, feature_dir: Path) -> Dict[str, Any]:
    sandboxcheck_dir = plugin_root / "skills" / "local-sandboxcheck"
    execution_outputs = sandboxcheck_dir / "execution_outputs"
    harness_dir = feature_dir / ".runs" / "local-sandbox-fix"
    return {
        "plugin_root": str(plugin_root),
        "working_dir": str(working_dir),
        "feature_dir": str(feature_dir),
        "sandboxcheck_dir": str(sandboxcheck_dir),
        "devops_src": str(working_dir / "devops_config.yaml"),
        "devops_dst": str(sandboxcheck_dir / "assets" / "input_biz_config" / "devops_config.yaml"),
        "run_ci_script": str(sandboxcheck_dir / "scripts" / "run_local_ci.py"),
        "execution_outputs": str(execution_outputs),
        "run_log": str(execution_outputs / "run.log"),
        "result_json": str(execution_outputs / "result.json"),
        "git_summary": str(execution_outputs / GIT_SUMMARY_NAME),
        "harness_dir": str(harness_dir),
        "max_iterations": 3,
        "stale_timeout_sec": 120,
        "global_timeout_sec": 5400,
    }


def _write_env_sh(harness_dir: Path, paths: Dict[str, Any]) -> None:
    lines = [
        "# Auto-generated by local_sandbox_fix_harness.py init",
        f'export CLAUDE_PLUGIN_ROOT="{paths["plugin_root"]}"',
        f'export CLAUDE_WORKING_DIR="{paths["working_dir"]}"',
        f'export HARNESS_DIR="{paths["harness_dir"]}"',
        f'export DEVOPS_SRC="{paths["devops_src"]}"',
        f'export DEVOPS_DST="{paths["devops_dst"]}"',
        f'export RUN_CI_SCRIPT="{paths["run_ci_script"]}"',
        f'export RUN_LOG="{paths["run_log"]}"',
        f'export RESULT_JSON="{paths["result_json"]}"',
        f'export SANDBOXCHECK_DIR="{paths["sandboxcheck_dir"]}"',
        f'export FEATURE_DIR="{paths["feature_dir"]}",',
    ]
    (harness_dir / "env.sh").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _new_gate_entry(iteration: int) -> Dict[str, Any]:
    return {"status": "pending", "gate_exit": None, "iteration": iteration, "notes": ""}


def _new_manifest(paths: Dict[str, Any], run_id: Optional[str] = None) -> Dict[str, Any]:
    iteration = 1
    gates = {step: _new_gate_entry(iteration if step in LOOP_STEPS else 0) for step in GATE_STEPS}
    return {
        "schema_version": "1",
        "run_id": run_id or str(uuid.uuid4()),
        "phase": "init",
        "iteration": iteration,
        "max_iterations": paths.get("max_iterations", 3),
        "current_step": GATE_STEPS[0],
        "status": "running",
        "started_at": _utc_now(),
        "updated_at": _utc_now(),
        "last_ci_code": None,
        "last_ci_id": None,
        "fix_started_at": None,
        "review_started_at": None,
        "gates": gates,
        "history": [],
    }


def _python_for_ci() -> str:
    for candidate in ("python3.8", "python3"):
        if shutil.which(candidate):
            return candidate
    return sys.executable


def _process_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def _git_has_changes(working_dir: Path) -> bool:
    for extra in ([], ["--cached"]):
        rc = subprocess.run(
            ["git", "-C", str(working_dir), "diff", "--quiet", *extra],
            capture_output=True,
        )
        if rc.returncode != 0:
            return True
    return False


def _gate_result(
    harness_dir: Path,
    manifest: Dict[str, Any],
    step: str,
    errors: List[str],
    next_action: str = "continue",
    **extra: Any,
) -> Dict[str, Any]:
    result: Dict[str, Any] = {
        "harness_dir": str(harness_dir),
        "step": step,
        "iteration": manifest.get("iteration", 1),
        "gate_exit": 0 if not errors else 1,
        "errors": errors,
        "next_action": "abort" if errors else next_action,
    }
    result.update(extra)
    return result


def _record_gate(harness_dir: Path, manifest: Dict[str, Any], step: str, result: Dict[str, Any]) -> None:
    iteration = manifest.get("iteration", 1)
    artifact = harness_dir / "steps" / f"iter-{iteration}-{step}.json"
    _write_json(artifact, result)
    manifest["gates"][step] = {
        "status": "passed" if result["gate_exit"] == 0 else "failed",
        "gate_exit": result["gate_exit"],
        "iteration": iteration,
        "artifact": str(artifact),
        "notes": "; ".join(result.get("errors") or []) or "ok",
        "updated_at": _utc_now(),
    }
    manifest["current_step"] = step
    _save_manifest(harness_dir, manifest)


def cmd_init(args: argparse.Namespace) -> int:
    plugin_root = _require_dir(args.plugin_root, "--plugin-root")
    working_dir = _require_dir(args.working_dir, "--working-dir")

    feature_arg = (getattr(args, "feature_dir", "") or "").strip()
    if feature_arg:
        feature_dir = Path(feature_arg).resolve()
        if not feature_dir.is_dir():
            print(json.dumps({"errors": [f"--feature-dir is not a directory: {feature_dir}"]}, ensure_ascii=False))
            return 1
    else:
        # 未显式传入：从记录文件解析（.active-feature / changes/*/.runs/.omnispec-state.json / 环境变量）
        feature_dir = _resolve_feature_dir_from_records(plugin_root, working_dir)
        if feature_dir is None:
            print(
                json.dumps(
                    {
                        "errors": [
                            "FEATURE_DIR 无法从记录文件解析；请先运行 specify/create-branch，或显式传 --feature-dir"
                        ]
                    },
                    ensure_ascii=False,
                )
            )
            return 1

    if not (plugin_root / "skills" / "local-sandbox-fix" / "SKILL.md").is_file():
        print(json.dumps({"errors": [f"local-sandbox-fix skill not found under {plugin_root}"]}, ensure_ascii=False))
        return 1

    paths = _build_paths(plugin_root, working_dir, feature_dir)
    harness_dir = Path(paths["harness_dir"])
    harness_dir.mkdir(parents=True, exist_ok=True)
    (harness_dir / "steps").mkdir(exist_ok=True)
    (harness_dir / "history").mkdir(exist_ok=True)

    _write_json(harness_dir / "paths.json", paths)
    _write_env_sh(harness_dir, paths)
    manifest = _new_manifest(paths, getattr(args, "run_id", None) or None)
    _save_manifest(harness_dir, manifest)

    print(json.dumps({"status": "ok", "harness_dir": str(harness_dir), "paths": str(harness_dir / "paths.json")}, ensure_ascii=False))
    return 0


def _gate_0_init(harness_dir: Path, paths: Dict[str, Any], manifest: Dict[str, Any]) -> Tuple[List[str], str]:
    """gate 0-init：地基就绪校验 + devops_config 文件初始化（cp / 缺失 skip）。

    返回 (errors, next_action)：
    - 地基校验 + cp 成功 → next_action=continue，置 phase=loop
    - devops_config 缺失 → next_action=skip（由 cmd_gate 走 _skip_devops_missing 成功收尾）
    - cp 失败 → errors 非空
    """
    errors: List[str] = []
    for key in ("plugin_root", "working_dir", "run_ci_script", "devops_src"):
        val = paths.get(key, "")
        if not val or not Path(val).is_absolute():
            errors.append(f"paths.json: {key} must be absolute path")
    run_ci = Path(paths["run_ci_script"])
    if not run_ci.is_file():
        errors.append(f"run_ci_script not found: {run_ci}")
    for name in ("paths.json", "env.sh", "run-manifest.json"):
        if not (harness_dir / name).is_file():
            errors.append(f"missing {name}")
    if errors:
        return errors, "continue"

    # 文件初始化：devops_config cp / 缺失 skip
    cp_errors, skipped = _prepare_devops_config(paths)
    if cp_errors:
        return cp_errors, "continue"
    if skipped:
        return [], "skip"

    manifest["phase"] = "loop"
    return [], "continue"


def _prepare_devops_config(paths: Dict[str, Any]) -> Tuple[List[str], bool]:
    """devops_config.yaml 视为可选（原 gate 1-prepare-config 逻辑，现由 gate 0-init 调用）。

    返回 (errors, skipped)：
    - src 存在 → cp 到 sandboxcheck 输入目录，skipped=False
    - src 缺失 → 不报错，skipped=True（由调用方走成功收尾，不进主循环）
    """
    errors: List[str] = []
    src = Path(paths["devops_src"])
    dst = Path(paths["devops_dst"])
    if not src.is_file():
        return [], True
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    if not dst.is_file():
        errors.append(f"copy failed: {dst}")
    elif dst.stat().st_mtime < src.stat().st_mtime:
        errors.append(f"devops_dst mtime older than src: {dst}")
    return errors, False


def _skip_devops_missing(harness_dir: Path, manifest: Dict[str, Any], paths: Dict[str, Any]) -> int:
    """devops_config.yaml 缺失：标记所有主循环 gate 为 skipped，成功收尾，不进主循环。

    0-init 已由调用方（gate 0-init 分支经 _record_gate）记录为 passed；此处只处理 loop steps。
    """
    manifest["skipped"] = True
    manifest["skip_reason"] = "devops_config.yaml 不存在，跳过本地 CI"
    manifest["phase"] = "success"
    skip_note = "skipped: devops_config.yaml 不存在"
    for skip_step in LOOP_STEPS:  # 2-start-ci ... 7-record-iteration
        manifest["gates"][skip_step] = {
            "status": "skipped",
            "gate_exit": 0,
            "iteration": manifest.get("iteration", 1),
            "notes": skip_note,
            "updated_at": _utc_now(),
        }
    manifest["current_step"] = "0-init"
    _save_manifest(harness_dir, manifest)
    return cmd_finalize(harness_dir, manifest, paths)


def _gate_2_start_ci(harness_dir: Path, paths: Dict[str, Any], manifest: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    run_log = Path(paths["run_log"])
    pid_file = harness_dir / "run_local_ci.pid"
    if pid_file.is_file():
        old_pid = int(pid_file.read_text(encoding="utf-8").strip() or "0")
        if _process_alive(old_pid):
            errors.append(f"CI already running with pid {old_pid}")
            return errors

    offset = run_log.stat().st_size if run_log.is_file() else 0
    mtime_before = run_log.stat().st_mtime if run_log.is_file() else 0.0
    session = {
        "iteration": manifest.get("iteration", 1),
        "run_log_path": str(run_log),
        "run_log_offset": offset,
        "run_log_mtime_before": mtime_before,
        "started_at": _utc_now(),
    }
    _write_json(harness_dir / "ci-session.json", session)

    python_bin = _python_for_ci()
    working_dir = paths["working_dir"]
    proc = subprocess.Popen(
        [python_bin, paths["run_ci_script"], working_dir],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    pid_file.write_text(str(proc.pid), encoding="utf-8")

    deadline = time.time() + 30
    started = False
    while time.time() < deadline:
        if _process_alive(proc.pid):
            started = True
        if run_log.is_file():
            tail = run_log.read_bytes()[offset:].decode("utf-8", errors="replace")
            if SESSION_START_MARKER in tail:
                started = True
                break
        if started and not _process_alive(proc.pid) and Path(paths["result_json"]).is_file():
            break
        time.sleep(2)

    if not pid_file.is_file():
        errors.append("run_local_ci.pid not written")
    elif not started:
        errors.append("CI did not start within 30s (no pid/log marker)")
    return errors


def _gate_3_wait_ci(harness_dir: Path, paths: Dict[str, Any]) -> Tuple[List[str], int]:
    wait_script = Path(__file__).resolve().parent / "wait_sandboxcheck.py"
    cmd = [
        sys.executable,
        str(wait_script),
        "--run-log",
        paths["run_log"],
        "--result-json",
        paths["result_json"],
        "--session-file",
        str(harness_dir / "ci-session.json"),
        "--pid-file",
        str(harness_dir / "run_local_ci.pid"),
        "--stale-timeout",
        str(paths.get("stale_timeout_sec", 120)),
        "--global-timeout",
        str(paths.get("global_timeout_sec", 5400)),
        "--poll-interval",
        "5",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        msg = proc.stdout.strip() or proc.stderr.strip() or f"wait exit {proc.returncode}"
        return [msg], proc.returncode
    return [], 0


def _parse_result(paths: Dict[str, Any], manifest: Dict[str, Any]) -> Tuple[List[str], str, Dict[str, Any]]:
    errors: List[str] = []
    result_path = Path(paths["result_json"])
    if not result_path.is_file():
        return [f"result.json missing: {result_path}"], "abort", {}

    try:
        ci_result = _read_json(result_path)
    except json.JSONDecodeError as exc:
        return [f"invalid result.json: {exc}"], "abort", {}

    code = ci_result.get("code")
    meta = ci_result.get("data", {}).get("meta", {}) or {}
    checks = ci_result.get("data", {}).get("checks", []) or []
    manifest["last_ci_code"] = code
    manifest["last_ci_id"] = meta.get("sandbox_ci_id")

    extra = {"ci_code": code, "ci_id": meta.get("sandbox_ci_id")}

    if code == 200:
        return [], "finalize", extra

    failed = [c for c in checks if c.get("check_result") == "failed"]
    fix_context = {
        "iteration": manifest.get("iteration", 1),
        "code": code,
        "message": ci_result.get("message", ""),
        "meta": {
            "sandbox_ci_id": meta.get("sandbox_ci_id"),
            "status": meta.get("status"),
            "duration": meta.get("duration"),
            "measure_path": meta.get("measure_path"),
        },
        "failed_checks": [],
        "git_summary_path": paths.get("git_summary", ""),
    }
    for check in failed:
        logs = check.get("check_log") or ""
        log_paths = [str(Path(p.strip()).resolve()) for p in str(logs).split(",") if p.strip()]
        fix_context["failed_checks"].append(
            {
                "check_type": check.get("check_type"),
                "check_result": check.get("check_result"),
                "check_info": check.get("check_info", ""),
                "check_log": log_paths,
            }
        )
    harness_dir = Path(paths["harness_dir"])
    fix_path = harness_dir / "fix-context.json"
    _write_json(fix_path, fix_context)
    extra["fix_context"] = str(fix_path)
    return [], "fix", extra


def _gate_5_fix_verify(paths: Dict[str, Any], manifest: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    working_dir = Path(paths["working_dir"])
    if not manifest.get("fix_started_at"):
        manifest["fix_started_at"] = _utc_now()
    if not _git_has_changes(working_dir):
        errors.append("修码后无变更")
    return errors


def _find_review_report(paths: Dict[str, Any]) -> Optional[Path]:
    candidates: List[Path] = []
    feature = (paths.get("feature_dir") or "").strip()
    working = Path(paths["working_dir"])
    if feature:
        fd = Path(feature)
        candidates.append(fd / "code-review.md")
        candidates.append(fd / ".runs" / "evaluations" / "code-review-summary.json")
    candidates.append(working / ".runs" / "evaluations" / "code-review-summary.json")
    for path in candidates:
        if path.is_file():
            return path.resolve()
    return None


def _gate_6_code_review(paths: Dict[str, Any], manifest: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    report = _find_review_report(paths)
    if report is None:
        errors.append("code-review 报告不存在")
        return errors
    fix_at = manifest.get("fix_started_at") or manifest.get("review_started_at")
    if fix_at:
        fix_ts = datetime.fromisoformat(fix_at.replace("Z", "+00:00")).timestamp()
        if report.stat().st_mtime <= fix_ts:
            errors.append(f"报告 mtime 不晚于 fix_started_at: {report}")
    if report.suffix == ".json":
        try:
            data = _read_json(report)
            verdict = (data.get("VERDICT") or data.get("verdict") or "").upper()
            if verdict == "BLOCK":
                errors.append("code-review VERDICT=BLOCK")
        except json.JSONDecodeError:
            errors.append(f"invalid review json: {report}")
    return errors


def _gate_7_record_iteration(harness_dir: Path, manifest: Dict[str, Any], paths: Dict[str, Any]) -> Tuple[List[str], str, int]:
    errors: List[str] = []
    iteration = manifest.get("iteration", 1)
    history_item = {
        "iteration": iteration,
        "ci_code": manifest.get("last_ci_code"),
        "ci_id": manifest.get("last_ci_id"),
        "ended_at": _utc_now(),
    }
    manifest.setdefault("history", []).append(history_item)
    _write_json(harness_dir / "history" / f"iter-{iteration}-summary.json", history_item)

    next_iteration = iteration + 1
    max_iter = manifest.get("max_iterations", 3)
    if manifest.get("last_ci_code") == 200:
        errors.append("unexpected record when CI passed")
        return errors, "abort", 1

    if next_iteration > max_iter:
        manifest["phase"] = "failed"
        manifest["status"] = "failed"
        _save_manifest(harness_dir, manifest)
        return [f"超过最大修复轮次 {max_iter}"], "abort", 20

    manifest["iteration"] = next_iteration
    manifest["fix_started_at"] = None
    manifest["review_started_at"] = None
    for step in LOOP_STEPS:
        manifest["gates"][step] = _new_gate_entry(next_iteration)

    for name in ("run_local_ci.pid", "ci-session.json"):
        p = harness_dir / name
        if p.is_file():
            p.unlink()

    _save_manifest(harness_dir, manifest)
    return [], "next_iteration", 0


def _write_workflow_status(paths: Dict[str, Any], harness_dir: Path, payload: Dict[str, Any]) -> None:
    feature = (paths.get("feature_dir") or "").strip()
    if not feature:
        return
    status_path = Path(feature) / ".runs" / "local-sandbox-fix-status.json"
    data = dict(payload)
    data["harness_dir"] = str(harness_dir)
    _write_json(status_path, data)


def _sync_workflow_progress(paths: Dict[str, Any], step_label: str = "") -> None:
    feature = (paths.get("feature_dir") or "").strip()
    plugin = Path(str(paths.get("plugin_root") or ""))
    state_py = plugin / "scripts" / "python" / "omnispec_state.py"
    if not feature or not state_py.is_file():
        return
    cmd = [sys.executable, str(state_py), "progress", "--feature-dir", feature]
    if step_label:
        cmd.extend(["--step", step_label])
    subprocess.run(cmd, check=False, capture_output=True)


def cmd_finalize(harness_dir: Path, manifest: Dict[str, Any], paths: Dict[str, Any]) -> int:
    manifest["phase"] = "success"
    manifest["status"] = "success"
    _save_manifest(harness_dir, manifest)
    summary = {
        "status": "success",
        "skipped": bool(manifest.get("skipped", False)),
        "skip_reason": manifest.get("skip_reason"),
        "ci_code": manifest.get("last_ci_code"),
        "ci_id": manifest.get("last_ci_id"),
        "iteration": manifest.get("iteration"),
        "finished_at": _utc_now(),
    }
    _write_json(harness_dir / "summary.json", summary)
    _write_workflow_status(paths, harness_dir, summary)
    _sync_workflow_progress(
        paths,
        step_label="Step 7 local-sandbox-fix harness 通过（待 workflow mark-complete）",
    )
    print(
        json.dumps(
            {
                "status": "success",
                "message": "local-sandbox-fix 通过",
                "sandbox_ci_id": manifest.get("last_ci_id"),
                "iteration": manifest.get("iteration"),
                "summary": str(harness_dir / "summary.json"),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


def cmd_gate(args: argparse.Namespace) -> int:
    harness_dir = _harness_dir_from_args(args)
    step = args.step
    if step not in GATE_STEPS:
        print(json.dumps({"errors": [f"unknown step: {step}"]}, ensure_ascii=False))
        return 2

    paths = _load_paths(harness_dir)
    manifest = _load_manifest(harness_dir)
    errors: List[str] = []
    next_action = "continue"
    extra: Dict[str, Any] = {}
    exit_code = 0

    if step == "0-init":
        errors, next_action = _gate_0_init(harness_dir, paths, manifest)
        # devops_config.yaml 缺失 → skip：标记主循环全 skipped 并成功收尾
        if not errors and next_action == "skip":
            _save_manifest(harness_dir, manifest)
            result = _gate_result(harness_dir, manifest, step, [], "skip", skipped=True)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            if args.record:
                _record_gate(harness_dir, manifest, step, result)
            return _skip_devops_missing(harness_dir, manifest, paths)
    elif step == "2-start-ci":
        errors = _gate_2_start_ci(harness_dir, paths, manifest)
    elif step == "3-wait-ci":
        errors, wait_code = _gate_3_wait_ci(harness_dir, paths)
        if wait_code != 0:
            result = _gate_result(harness_dir, manifest, step, errors, "abort")
            print(json.dumps(result, ensure_ascii=False, indent=2))
            if args.record:
                _record_gate(harness_dir, manifest, step, result)
            return wait_code
    elif step == "4-parse-result":
        errors, next_action, extra = _parse_result(paths, manifest)
        _save_manifest(harness_dir, manifest)
        if not errors and next_action == "finalize":
            result = _gate_result(harness_dir, manifest, step, [], "finalize", **extra)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            if args.record:
                _record_gate(harness_dir, manifest, step, result)
            return cmd_finalize(harness_dir, manifest, paths)
    elif step == "5-fix-verify":
        errors = _gate_5_fix_verify(paths, manifest)
        if not errors:
            next_action = "code-review"
    elif step == "6-code-review-gate":
        errors = _gate_6_code_review(paths, manifest)
    elif step == "7-record-iteration":
        errors, next_action, rec_code = _gate_7_record_iteration(harness_dir, manifest, paths)
        if rec_code != 0:
            result = _gate_result(harness_dir, manifest, step, errors, next_action)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            if args.record:
                _record_gate(harness_dir, manifest, step, result)
            return rec_code

    result = _gate_result(harness_dir, manifest, step, errors, next_action, **extra)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if args.record:
        _record_gate(harness_dir, manifest, step, result)
        if step == "5-fix-verify" and not errors:
            _save_manifest(harness_dir, manifest)
    elif step in ("4-parse-result", "5-fix-verify", "7-record-iteration"):
        _save_manifest(harness_dir, manifest)
    return 0 if not errors else 2


def cmd_resume(args: argparse.Namespace) -> int:
    harness_dir = _harness_dir_from_args(args)
    manifest = _load_manifest(harness_dir)
    iteration = manifest.get("iteration", 1)
    pending: List[str] = []
    for step in GATE_STEPS:
        info = manifest.get("gates", {}).get(step, {})
        if step in LOOP_STEPS and info.get("iteration", iteration) != iteration:
            continue
        if info.get("status") != "passed" or info.get("gate_exit") != 0:
            pending.append(step)

    next_action = "continue"
    if manifest.get("phase") == "success":
        next_action = "finalize"
    elif pending:
        if "5-fix-verify" in pending and manifest.get("last_ci_code") not in (None, 200):
            fix_ctx = harness_dir / "fix-context.json"
            if fix_ctx.is_file():
                next_action = "fix"
        elif "6-code-review-gate" in pending and "5-fix-verify" not in pending:
            next_action = "code-review"

    out = {
        "phase": manifest.get("phase"),
        "iteration": iteration,
        "max_iterations": manifest.get("max_iterations", 3),
        "pending_steps": pending,
        "next_action": next_action,
        "current_step": pending[0] if pending else None,
        "run_id": manifest.get("run_id"),
    }
    print(json.dumps(out, ensure_ascii=False, indent=2))
    return 0


def cmd_abort(args: argparse.Namespace) -> int:
    harness_dir = _harness_dir_from_args(args)
    manifest = _load_manifest(harness_dir)
    paths = _load_paths(harness_dir)
    manifest["phase"] = "failed"
    manifest["status"] = "failed"
    manifest["abort_reason"] = args.reason or "aborted"
    _save_manifest(harness_dir, manifest)
    _write_json(
        harness_dir / "summary.json",
        {"status": "failed", "reason": manifest["abort_reason"], "finished_at": _utc_now()},
    )
    _write_workflow_status(
        paths,
        harness_dir,
        {"status": "failed", "reason": manifest["abort_reason"], "finished_at": _utc_now()},
    )
    print(json.dumps({"status": "aborted", "reason": manifest["abort_reason"]}, ensure_ascii=False))
    return 1


def _resolve_working_dir_from_feature(feature_dir: Path) -> Optional[Path]:
    env_sh = feature_dir / ".runs" / "env.sh"
    if env_sh.is_file():
        for line in env_sh.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("export CLAUDE_WORKING_DIR="):
                val = line.split("=", 1)[1].strip().strip('"').strip("'")
                if val:
                    return Path(val).resolve()
    paths_file = feature_dir / ".runs" / "paths.json"
    if paths_file.is_file():
        try:
            data = _read_json(paths_file)
            wd = (data.get("working_dir") or data.get("CLAUDE_WORKING_DIR") or "").strip()
            if wd:
                return Path(wd).resolve()
        except json.JSONDecodeError:
            pass
    return None


def cmd_workflow_gate(args: argparse.Namespace) -> int:
    check = args.check
    feature_dir = Path(args.feature_dir).resolve()
    if not feature_dir.is_dir():
        print(json.dumps({"gate_exit": 1, "errors": [f"feature_dir not found: {feature_dir}"]}, ensure_ascii=False))
        return 1

    working_dir = Path(args.working_dir).resolve() if getattr(args, "working_dir", None) else None
    if working_dir is None:
        working_dir = _resolve_working_dir_from_feature(feature_dir)
    if working_dir is None or not working_dir.is_dir():
        print(json.dumps({"gate_exit": 1, "errors": ["CLAUDE_WORKING_DIR unresolved"]}, ensure_ascii=False))
        return 1

    errors: List[str] = []
    if check == "pre":
        # devops_config.yaml 视为可选；缺失由 gate 0-init（_skip_devops_missing）走 skip 路径
        # pre 仅校验 working_dir 已解析（上面完成），不再因配置缺失拦截入口
        pass
    elif check == "complete":
        status_file = feature_dir / ".runs" / "local-sandbox-fix-status.json"
        if not status_file.is_file():
            errors.append(f"workflow status 缺失: {status_file}")
        else:
            try:
                data = _read_json(status_file)
                if data.get("status") != "success":
                    errors.append(f"local-sandbox-fix status={data.get('status')}")
            except json.JSONDecodeError as exc:
                errors.append(f"invalid status json: {exc}")
        summary = feature_dir / ".runs" / "local-sandbox-fix" / "summary.json"
        if summary.is_file():
            try:
                if _read_json(summary).get("status") != "success":
                    errors.append(f"harness summary not success: {summary}")
            except json.JSONDecodeError:
                errors.append(f"invalid harness summary: {summary}")
    else:
        print(json.dumps({"gate_exit": 2, "errors": [f"unknown check: {check}"]}, ensure_ascii=False))
        return 2

    result = {"check": check, "feature_dir": str(feature_dir), "working_dir": str(working_dir), "gate_exit": 0 if not errors else 1, "errors": errors}
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if not errors else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="local-sandbox-fix harness")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="初始化 harness 目录")
    p_init.add_argument("--plugin-root", required=True)
    p_init.add_argument("--working-dir", required=True)
    p_init.add_argument("--feature-dir", default="")
    p_init.add_argument("--run-id", default="")

    p_gate = sub.add_parser("gate", help="分步门禁")
    p_gate.add_argument("--harness-dir", default="")
    p_gate.add_argument("--working-dir", default="")
    p_gate.add_argument("--step", required=True, choices=GATE_STEPS)
    p_gate.add_argument("--record", action="store_true")

    p_resume = sub.add_parser("resume", help="断点续跑")
    p_resume.add_argument("--harness-dir", default="")
    p_resume.add_argument("--working-dir", default="")

    p_fin = sub.add_parser("finalize", help="成功收尾")
    p_fin.add_argument("--harness-dir", default="")
    p_fin.add_argument("--working-dir", default="")

    p_abort = sub.add_parser("abort", help="失败中止")
    p_abort.add_argument("--harness-dir", default="")
    p_abort.add_argument("--working-dir", default="")
    p_abort.add_argument("--reason", default="")

    p_wfg = sub.add_parser("workflow-gate", help="express workflow 门禁（pre/complete）")
    p_wfg.add_argument("--feature-dir", required=True)
    p_wfg.add_argument("--working-dir", default="")
    p_wfg.add_argument("--check", required=True, choices=["pre", "complete"])

    args = parser.parse_args()
    if args.command == "init":
        return cmd_init(args)
    if args.command == "gate":
        return cmd_gate(args)
    if args.command == "resume":
        return cmd_resume(args)
    if args.command == "abort":
        return cmd_abort(args)
    if args.command == "workflow-gate":
        return cmd_workflow_gate(args)
    if args.command == "finalize":
        harness_dir = _harness_dir_from_args(args)
        return cmd_finalize(harness_dir, _load_manifest(harness_dir), _load_paths(harness_dir))
    return 1


if __name__ == "__main__":
    sys.exit(main())
